#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 0.1.{build}.0
image: Visual Studio 2017
install:
    - ps: docker -v

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: docker build -t travisez13/microsoft.windowsservercore.git:latest ./microsoft/windowsservercore/git
    - ps: docker build -t "travisez13/microsoft.windowsservercore.git:$env:APPVEYOR_BUILD_VERSION" ./microsoft/windowsservercore/git

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script:
    - ps: |
        if($env:docker_user -and $env:docker_password)
        {
            docker login --username $env:docker_user --password $env:docker_password
            docker push "travisez13/microsoft.windowsservercore.git:$env:APPVEYOR_BUILD_VERSION"
            docker push travisez13/microsoft.windowsservercore.git:latest
        }
