#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 2.5.{build}.0
image: Visual Studio 2017
install:
    - ps: docker -v

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: docker build -t travisez13/docker:windowsservercore_git ./microsoft/windowsservercore/git

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script:
    - ps: |
        if($env:docker_user -and $env:docker_password)
        {
            docker login --username $env:docker_user --password $env:docker_password
            docker push travisez13/docker:windowsservercore_git
        }
        docker save travisez13/docker:windowsservercore_git > travisez13_docker_windowsservercore_git.tgz
        push-appveyorartifact travisez13_docker_windowsservercore_git.tgz
